apiVersion: apps/v1
kind: Deployment
metadata:
  name: laborator-deployment2
spec:
  replicas: 4
  selector:
    matchLabels:
      app: laborator
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 4
  template:
    metadata:
      labels:
        app: laborator
    spec:
      containers:
      - image: sap4k/laborator:lab_modificari
        name: laborator-container2
        ports:
        - containerPort: 8080